# Generated by Django 4.1.5 on 2023-01-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
